//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export const CATALOG_API_URL = new InjectionToken<string>('CATALOG_API_URL');

@Injectable()
export class CatalogBrandClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(CATALOG_API_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    getCatalogBrand(catalogBrandId: string): Observable<CatalogBrandReadModel> {
        let url_ = this.baseUrl + "/api/CatalogBrand/{catalogBrandId}";
        if (catalogBrandId === undefined || catalogBrandId === null)
            throw new Error("The parameter 'catalogBrandId' must be defined.");
        url_ = url_.replace("{catalogBrandId}", encodeURIComponent("" + catalogBrandId));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetCatalogBrand(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetCatalogBrand(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<CatalogBrandReadModel>;
                }
            } else
                return _observableThrow(response_) as any as Observable<CatalogBrandReadModel>;
        }));
    }

    protected processGetCatalogBrand(response: HttpResponseBase): Observable<CatalogBrandReadModel> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = CatalogBrandReadModel.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("A server side error occurred.", status, _responseText, _headers, result404);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = CatalogDomainErrorDTO.fromJS(resultData400);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    updateCatalogBrand(catalogBrandId: string, catalogBrand: CatalogBrandDTO): Observable<CatalogBrandReadModel> {
        let url_ = this.baseUrl + "/api/CatalogBrand/{catalogBrandId}";
        if (catalogBrandId === undefined || catalogBrandId === null)
            throw new Error("The parameter 'catalogBrandId' must be defined.");
        url_ = url_.replace("{catalogBrandId}", encodeURIComponent("" + catalogBrandId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(catalogBrand);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("put", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUpdateCatalogBrand(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUpdateCatalogBrand(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<CatalogBrandReadModel>;
                }
            } else
                return _observableThrow(response_) as any as Observable<CatalogBrandReadModel>;
        }));
    }

    protected processUpdateCatalogBrand(response: HttpResponseBase): Observable<CatalogBrandReadModel> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 201) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result201: any = null;
            let resultData201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result201 = CatalogBrandReadModel.fromJS(resultData201);
            return _observableOf(result201);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("A server side error occurred.", status, _responseText, _headers, result404);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = CatalogDomainErrorDTO.fromJS(resultData400);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    deleteCatalogBrand(catalogBrandId: string): Observable<void> {
        let url_ = this.baseUrl + "/api/CatalogBrand/{catalogBrandId}";
        if (catalogBrandId === undefined || catalogBrandId === null)
            throw new Error("The parameter 'catalogBrandId' must be defined.");
        url_ = url_.replace("{catalogBrandId}", encodeURIComponent("" + catalogBrandId));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
            })
        };

        return this.http.request("delete", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processDeleteCatalogBrand(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processDeleteCatalogBrand(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<void>;
                }
            } else
                return _observableThrow(response_) as any as Observable<void>;
        }));
    }

    protected processDeleteCatalogBrand(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return _observableOf(null as any);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("A server side error occurred.", status, _responseText, _headers, result404);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = CatalogDomainErrorDTO.fromJS(resultData400);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    createCatalogBrand(catalogBrand: CatalogBrandDTO): Observable<CatalogBrandReadModel> {
        let url_ = this.baseUrl + "/api/CatalogBrand";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(catalogBrand);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processCreateCatalogBrand(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processCreateCatalogBrand(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<CatalogBrandReadModel>;
                }
            } else
                return _observableThrow(response_) as any as Observable<CatalogBrandReadModel>;
        }));
    }

    protected processCreateCatalogBrand(response: HttpResponseBase): Observable<CatalogBrandReadModel> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 201) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result201: any = null;
            let resultData201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result201 = CatalogBrandReadModel.fromJS(resultData201);
            return _observableOf(result201);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    getCatalogBrands(orderByDirection: OrderByDirections | undefined, pageIndex: number | undefined, pageSize: number | undefined): Observable<ListCatalogBrandResult> {
        let url_ = this.baseUrl + "/api/CatalogBrand/list?";
        if (orderByDirection === null)
            throw new Error("The parameter 'orderByDirection' cannot be null.");
        else if (orderByDirection !== undefined)
            url_ += "OrderByDirection=" + encodeURIComponent("" + orderByDirection) + "&";
        if (pageIndex === null)
            throw new Error("The parameter 'pageIndex' cannot be null.");
        else if (pageIndex !== undefined)
            url_ += "PageIndex=" + encodeURIComponent("" + pageIndex) + "&";
        if (pageSize === null)
            throw new Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "PageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetCatalogBrands(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetCatalogBrands(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<ListCatalogBrandResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<ListCatalogBrandResult>;
        }));
    }

    protected processGetCatalogBrands(response: HttpResponseBase): Observable<ListCatalogBrandResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ListCatalogBrandResult.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

@Injectable()
export class CatalogItemClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(CATALOG_API_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    getCatalogItem(catalogItemId: string): Observable<CatalogItemReadModel> {
        let url_ = this.baseUrl + "/api/CatalogItem/{catalogItemId}";
        if (catalogItemId === undefined || catalogItemId === null)
            throw new Error("The parameter 'catalogItemId' must be defined.");
        url_ = url_.replace("{catalogItemId}", encodeURIComponent("" + catalogItemId));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetCatalogItem(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetCatalogItem(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<CatalogItemReadModel>;
                }
            } else
                return _observableThrow(response_) as any as Observable<CatalogItemReadModel>;
        }));
    }

    protected processGetCatalogItem(response: HttpResponseBase): Observable<CatalogItemReadModel> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = CatalogItemReadModel.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("A server side error occurred.", status, _responseText, _headers, result404);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    updateCatalogItem(catalogItemId: string, catalogItem: CatalogItemDTO): Observable<CatalogItemReadModel> {
        let url_ = this.baseUrl + "/api/CatalogItem/{catalogItemId}";
        if (catalogItemId === undefined || catalogItemId === null)
            throw new Error("The parameter 'catalogItemId' must be defined.");
        url_ = url_.replace("{catalogItemId}", encodeURIComponent("" + catalogItemId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(catalogItem);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("put", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUpdateCatalogItem(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUpdateCatalogItem(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<CatalogItemReadModel>;
                }
            } else
                return _observableThrow(response_) as any as Observable<CatalogItemReadModel>;
        }));
    }

    protected processUpdateCatalogItem(response: HttpResponseBase): Observable<CatalogItemReadModel> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = CatalogItemReadModel.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("A server side error occurred.", status, _responseText, _headers, result404);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = CatalogDomainErrorDTO.fromJS(resultData400);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    deleteCatalogItem(catalogItemId: string): Observable<void> {
        let url_ = this.baseUrl + "/api/CatalogItem/{catalogItemId}";
        if (catalogItemId === undefined || catalogItemId === null)
            throw new Error("The parameter 'catalogItemId' must be defined.");
        url_ = url_.replace("{catalogItemId}", encodeURIComponent("" + catalogItemId));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
            })
        };

        return this.http.request("delete", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processDeleteCatalogItem(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processDeleteCatalogItem(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<void>;
                }
            } else
                return _observableThrow(response_) as any as Observable<void>;
        }));
    }

    protected processDeleteCatalogItem(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return _observableOf(null as any);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("A server side error occurred.", status, _responseText, _headers, result404);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = CatalogDomainErrorDTO.fromJS(resultData400);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    createCatalogItem(catalogItem: CatalogItemDTO): Observable<CatalogItemReadModel> {
        let url_ = this.baseUrl + "/api/CatalogItem";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(catalogItem);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processCreateCatalogItem(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processCreateCatalogItem(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<CatalogItemReadModel>;
                }
            } else
                return _observableThrow(response_) as any as Observable<CatalogItemReadModel>;
        }));
    }

    protected processCreateCatalogItem(response: HttpResponseBase): Observable<CatalogItemReadModel> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 201) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result201: any = null;
            let resultData201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result201 = CatalogItemReadModel.fromJS(resultData201);
            return _observableOf(result201);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = CatalogDomainErrorDTO.fromJS(resultData400);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    getCatalogItems(orderBy: ListCatalogItemOrderBy | undefined, orderByDirection: OrderByDirections | undefined, pageIndex: number | undefined, pageSize: number | undefined, nameFilter: string | null | undefined, brandFilter: string | null | undefined, typeFilter: string | null | undefined): Observable<ListCatalogItemResult> {
        let url_ = this.baseUrl + "/api/CatalogItem/list?";
        if (orderBy === null)
            throw new Error("The parameter 'orderBy' cannot be null.");
        else if (orderBy !== undefined)
            url_ += "OrderBy=" + encodeURIComponent("" + orderBy) + "&";
        if (orderByDirection === null)
            throw new Error("The parameter 'orderByDirection' cannot be null.");
        else if (orderByDirection !== undefined)
            url_ += "OrderByDirection=" + encodeURIComponent("" + orderByDirection) + "&";
        if (pageIndex === null)
            throw new Error("The parameter 'pageIndex' cannot be null.");
        else if (pageIndex !== undefined)
            url_ += "PageIndex=" + encodeURIComponent("" + pageIndex) + "&";
        if (pageSize === null)
            throw new Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "PageSize=" + encodeURIComponent("" + pageSize) + "&";
        if (nameFilter !== undefined && nameFilter !== null)
            url_ += "NameFilter=" + encodeURIComponent("" + nameFilter) + "&";
        if (brandFilter !== undefined && brandFilter !== null)
            url_ += "BrandFilter=" + encodeURIComponent("" + brandFilter) + "&";
        if (typeFilter !== undefined && typeFilter !== null)
            url_ += "TypeFilter=" + encodeURIComponent("" + typeFilter) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetCatalogItems(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetCatalogItems(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<ListCatalogItemResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<ListCatalogItemResult>;
        }));
    }

    protected processGetCatalogItems(response: HttpResponseBase): Observable<ListCatalogItemResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ListCatalogItemResult.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

@Injectable()
export class CatalogTypeClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(CATALOG_API_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    getCatalogType(catalogTypeId: string): Observable<CatalogTypeReadModel> {
        let url_ = this.baseUrl + "/api/CatalogType/{catalogTypeId}";
        if (catalogTypeId === undefined || catalogTypeId === null)
            throw new Error("The parameter 'catalogTypeId' must be defined.");
        url_ = url_.replace("{catalogTypeId}", encodeURIComponent("" + catalogTypeId));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetCatalogType(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetCatalogType(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<CatalogTypeReadModel>;
                }
            } else
                return _observableThrow(response_) as any as Observable<CatalogTypeReadModel>;
        }));
    }

    protected processGetCatalogType(response: HttpResponseBase): Observable<CatalogTypeReadModel> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = CatalogTypeReadModel.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("A server side error occurred.", status, _responseText, _headers, result404);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    updateCatalogType(catalogTypeId: string, catalogType: CatalogTypeDTO): Observable<CatalogTypeReadModel> {
        let url_ = this.baseUrl + "/api/CatalogType/{catalogTypeId}";
        if (catalogTypeId === undefined || catalogTypeId === null)
            throw new Error("The parameter 'catalogTypeId' must be defined.");
        url_ = url_.replace("{catalogTypeId}", encodeURIComponent("" + catalogTypeId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(catalogType);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("put", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUpdateCatalogType(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUpdateCatalogType(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<CatalogTypeReadModel>;
                }
            } else
                return _observableThrow(response_) as any as Observable<CatalogTypeReadModel>;
        }));
    }

    protected processUpdateCatalogType(response: HttpResponseBase): Observable<CatalogTypeReadModel> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 201) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result201: any = null;
            let resultData201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result201 = CatalogTypeReadModel.fromJS(resultData201);
            return _observableOf(result201);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("A server side error occurred.", status, _responseText, _headers, result404);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = CatalogDomainErrorDTO.fromJS(resultData400);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    deleteCatalogType(catalogTypeId: string): Observable<void> {
        let url_ = this.baseUrl + "/api/CatalogType/{catalogTypeId}";
        if (catalogTypeId === undefined || catalogTypeId === null)
            throw new Error("The parameter 'catalogTypeId' must be defined.");
        url_ = url_.replace("{catalogTypeId}", encodeURIComponent("" + catalogTypeId));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
            })
        };

        return this.http.request("delete", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processDeleteCatalogType(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processDeleteCatalogType(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<void>;
                }
            } else
                return _observableThrow(response_) as any as Observable<void>;
        }));
    }

    protected processDeleteCatalogType(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return _observableOf(null as any);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("A server side error occurred.", status, _responseText, _headers, result404);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = CatalogDomainErrorDTO.fromJS(resultData400);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    createCatalogType(catalogType: CatalogTypeDTO): Observable<CatalogTypeReadModel> {
        let url_ = this.baseUrl + "/api/CatalogType";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(catalogType);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processCreateCatalogType(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processCreateCatalogType(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<CatalogTypeReadModel>;
                }
            } else
                return _observableThrow(response_) as any as Observable<CatalogTypeReadModel>;
        }));
    }

    protected processCreateCatalogType(response: HttpResponseBase): Observable<CatalogTypeReadModel> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 201) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result201: any = null;
            let resultData201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result201 = CatalogTypeReadModel.fromJS(resultData201);
            return _observableOf(result201);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = CatalogDomainErrorDTO.fromJS(resultData400);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    getCatalogTypes(orderByDirection: OrderByDirections | undefined, pageIndex: number | undefined, pageSize: number | undefined): Observable<ListCatalogTypeResult> {
        let url_ = this.baseUrl + "/api/CatalogType/list?";
        if (orderByDirection === null)
            throw new Error("The parameter 'orderByDirection' cannot be null.");
        else if (orderByDirection !== undefined)
            url_ += "OrderByDirection=" + encodeURIComponent("" + orderByDirection) + "&";
        if (pageIndex === null)
            throw new Error("The parameter 'pageIndex' cannot be null.");
        else if (pageIndex !== undefined)
            url_ += "PageIndex=" + encodeURIComponent("" + pageIndex) + "&";
        if (pageSize === null)
            throw new Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "PageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetCatalogTypes(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetCatalogTypes(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<ListCatalogTypeResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<ListCatalogTypeResult>;
        }));
    }

    protected processGetCatalogTypes(response: HttpResponseBase): Observable<ListCatalogTypeResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ListCatalogTypeResult.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

export class CatalogBrandReadModel implements ICatalogBrandReadModel {
    ts?: string;
    id?: string;
    brand?: string;

    constructor(data?: ICatalogBrandReadModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.ts = _data["ts"];
            this.id = _data["id"];
            this.brand = _data["brand"];
        }
    }

    static fromJS(data: any): CatalogBrandReadModel {
        data = typeof data === 'object' ? data : {};
        let result = new CatalogBrandReadModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["ts"] = this.ts;
        data["id"] = this.id;
        data["brand"] = this.brand;
        return data;
    }
}

export interface ICatalogBrandReadModel {
    ts?: string;
    id?: string;
    brand?: string;
}

export class ProblemDetails implements IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;

    constructor(data?: IProblemDetails) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.type = _data["type"];
            this.title = _data["title"];
            this.status = _data["status"];
            this.detail = _data["detail"];
            this.instance = _data["instance"];
        }
    }

    static fromJS(data: any): ProblemDetails {
        data = typeof data === 'object' ? data : {};
        let result = new ProblemDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["type"] = this.type;
        data["title"] = this.title;
        data["status"] = this.status;
        data["detail"] = this.detail;
        data["instance"] = this.instance;
        return data;
    }
}

export interface IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;
}

export class CatalogDomainErrorDTO implements ICatalogDomainErrorDTO {
    errorType?: string;

    constructor(data?: ICatalogDomainErrorDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.errorType = _data["errorType"];
        }
    }

    static fromJS(data: any): CatalogDomainErrorDTO {
        data = typeof data === 'object' ? data : {};
        let result = new CatalogDomainErrorDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["errorType"] = this.errorType;
        return data;
    }
}

export interface ICatalogDomainErrorDTO {
    errorType?: string;
}

export class CatalogBrandDTO implements ICatalogBrandDTO {
    brand?: string;
    ts?: string | undefined;

    constructor(data?: ICatalogBrandDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.brand = _data["brand"];
            this.ts = _data["ts"];
        }
    }

    static fromJS(data: any): CatalogBrandDTO {
        data = typeof data === 'object' ? data : {};
        let result = new CatalogBrandDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["brand"] = this.brand;
        data["ts"] = this.ts;
        return data;
    }
}

export interface ICatalogBrandDTO {
    brand?: string;
    ts?: string | undefined;
}

export class ListCatalogBrandResult implements IListCatalogBrandResult {
    catalogBrands?: CatalogBrandReadModel[];
    totalCount?: number;

    constructor(data?: IListCatalogBrandResult) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["catalogBrands"])) {
                this.catalogBrands = [] as any;
                for (let item of _data["catalogBrands"])
                    this.catalogBrands!.push(CatalogBrandReadModel.fromJS(item));
            }
            this.totalCount = _data["totalCount"];
        }
    }

    static fromJS(data: any): ListCatalogBrandResult {
        data = typeof data === 'object' ? data : {};
        let result = new ListCatalogBrandResult();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.catalogBrands)) {
            data["catalogBrands"] = [];
            for (let item of this.catalogBrands)
                data["catalogBrands"].push(item.toJSON());
        }
        data["totalCount"] = this.totalCount;
        return data;
    }
}

export interface IListCatalogBrandResult {
    catalogBrands?: CatalogBrandReadModel[];
    totalCount?: number;
}

export enum OrderByDirections {
    ASC = 0,
    DESC = 1,
}

export class CatalogItemReadModel implements ICatalogItemReadModel {
    ts?: string;
    id?: string;
    name?: string;
    description?: string | undefined;
    price?: number | undefined;
    pictureUri?: string | undefined;
    catalogType?: CatalogTypeReadModel;
    catalogBrand?: CatalogBrandReadModel;

    constructor(data?: ICatalogItemReadModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.ts = _data["ts"];
            this.id = _data["id"];
            this.name = _data["name"];
            this.description = _data["description"];
            this.price = _data["price"];
            this.pictureUri = _data["pictureUri"];
            this.catalogType = _data["catalogType"] ? CatalogTypeReadModel.fromJS(_data["catalogType"]) : <any>undefined;
            this.catalogBrand = _data["catalogBrand"] ? CatalogBrandReadModel.fromJS(_data["catalogBrand"]) : <any>undefined;
        }
    }

    static fromJS(data: any): CatalogItemReadModel {
        data = typeof data === 'object' ? data : {};
        let result = new CatalogItemReadModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["ts"] = this.ts;
        data["id"] = this.id;
        data["name"] = this.name;
        data["description"] = this.description;
        data["price"] = this.price;
        data["pictureUri"] = this.pictureUri;
        data["catalogType"] = this.catalogType ? this.catalogType.toJSON() : <any>undefined;
        data["catalogBrand"] = this.catalogBrand ? this.catalogBrand.toJSON() : <any>undefined;
        return data;
    }
}

export interface ICatalogItemReadModel {
    ts?: string;
    id?: string;
    name?: string;
    description?: string | undefined;
    price?: number | undefined;
    pictureUri?: string | undefined;
    catalogType?: CatalogTypeReadModel;
    catalogBrand?: CatalogBrandReadModel;
}

export class CatalogTypeReadModel implements ICatalogTypeReadModel {
    ts?: string;
    id?: string;
    type?: string;

    constructor(data?: ICatalogTypeReadModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.ts = _data["ts"];
            this.id = _data["id"];
            this.type = _data["type"];
        }
    }

    static fromJS(data: any): CatalogTypeReadModel {
        data = typeof data === 'object' ? data : {};
        let result = new CatalogTypeReadModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["ts"] = this.ts;
        data["id"] = this.id;
        data["type"] = this.type;
        return data;
    }
}

export interface ICatalogTypeReadModel {
    ts?: string;
    id?: string;
    type?: string;
}

export class CatalogItemDTO implements ICatalogItemDTO {
    name?: string | undefined;
    description?: string | undefined;
    itemPrice?: number | undefined;
    pictureUri?: string | undefined;
    typeId?: string;
    brandId?: string;
    ts?: string | undefined;

    constructor(data?: ICatalogItemDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.description = _data["description"];
            this.itemPrice = _data["itemPrice"];
            this.pictureUri = _data["pictureUri"];
            this.typeId = _data["typeId"];
            this.brandId = _data["brandId"];
            this.ts = _data["ts"];
        }
    }

    static fromJS(data: any): CatalogItemDTO {
        data = typeof data === 'object' ? data : {};
        let result = new CatalogItemDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["description"] = this.description;
        data["itemPrice"] = this.itemPrice;
        data["pictureUri"] = this.pictureUri;
        data["typeId"] = this.typeId;
        data["brandId"] = this.brandId;
        data["ts"] = this.ts;
        return data;
    }
}

export interface ICatalogItemDTO {
    name?: string | undefined;
    description?: string | undefined;
    itemPrice?: number | undefined;
    pictureUri?: string | undefined;
    typeId?: string;
    brandId?: string;
    ts?: string | undefined;
}

export class ListCatalogItemResult implements IListCatalogItemResult {
    catalogItems?: CatalogItemReadModel[];
    totalCount?: number;

    constructor(data?: IListCatalogItemResult) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["catalogItems"])) {
                this.catalogItems = [] as any;
                for (let item of _data["catalogItems"])
                    this.catalogItems!.push(CatalogItemReadModel.fromJS(item));
            }
            this.totalCount = _data["totalCount"];
        }
    }

    static fromJS(data: any): ListCatalogItemResult {
        data = typeof data === 'object' ? data : {};
        let result = new ListCatalogItemResult();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.catalogItems)) {
            data["catalogItems"] = [];
            for (let item of this.catalogItems)
                data["catalogItems"].push(item.toJSON());
        }
        data["totalCount"] = this.totalCount;
        return data;
    }
}

export interface IListCatalogItemResult {
    catalogItems?: CatalogItemReadModel[];
    totalCount?: number;
}

export enum ListCatalogItemOrderBy {
    Name = 0,
    Brand = 1,
    Type = 2,
    Price = 3,
}

export class CatalogTypeDTO implements ICatalogTypeDTO {
    type?: string;
    ts?: string | undefined;

    constructor(data?: ICatalogTypeDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.type = _data["type"];
            this.ts = _data["ts"];
        }
    }

    static fromJS(data: any): CatalogTypeDTO {
        data = typeof data === 'object' ? data : {};
        let result = new CatalogTypeDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["type"] = this.type;
        data["ts"] = this.ts;
        return data;
    }
}

export interface ICatalogTypeDTO {
    type?: string;
    ts?: string | undefined;
}

export class ListCatalogTypeResult implements IListCatalogTypeResult {
    catalogTypes?: CatalogTypeReadModel[];
    totalCount?: number;

    constructor(data?: IListCatalogTypeResult) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["catalogTypes"])) {
                this.catalogTypes = [] as any;
                for (let item of _data["catalogTypes"])
                    this.catalogTypes!.push(CatalogTypeReadModel.fromJS(item));
            }
            this.totalCount = _data["totalCount"];
        }
    }

    static fromJS(data: any): ListCatalogTypeResult {
        data = typeof data === 'object' ? data : {};
        let result = new ListCatalogTypeResult();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.catalogTypes)) {
            data["catalogTypes"] = [];
            for (let item of this.catalogTypes)
                data["catalogTypes"].push(item.toJSON());
        }
        data["totalCount"] = this.totalCount;
        return data;
    }
}

export interface IListCatalogTypeResult {
    catalogTypes?: CatalogTypeReadModel[];
    totalCount?: number;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new ApiException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((event.target as any).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}
