# RELEASE PIPELINE (Docker Images Deployment)

resources:
  repositories:
  - repository: self
    trigger: none
  pipelines:
  - pipeline: eshop-on-microservices-ci-docker
    source: eshop-on-microservices-ci-docker

variables:
- group: microservices-variable-group

- name: azureserviceconnection
  value: 'azure-docker-spn'
- name: suffix
  value: ${{ split(variables['System.TeamProjectId'], '-')[0]}} # Pseudo - random string based on project Id
- name: storageAccountName
  value: 'storageacc$(suffix)'
- name: eshopProxyConfigFileShareName 
  value: 'eshopproxy'
- name: eshopEmployeePortalProxyConfigFileShareName
  value: 'eshopemployeeportalproxy'
- name: eshopProxyConfigurationFile
  value: '$(Pipeline.Workspace)/eshop-on-microservices-ci-docker/Envoy/envoy-azure-docker.yaml'
- name: eshopEmployeePortalProxyConfigurationFile
  value: '$(Pipeline.Workspace)/eshop-on-microservices-ci-docker/Envoy/envoy-employee-portal-azure-docker.yaml'
- name: eshopAppName
  value: 'eshop-$(suffix)'
- name: eshopEmployeePortalAppName
  value: 'eshop-employee-portal-$(suffix)'
- name: customerPortalContainerAppName
  value: 'customer-portal-static-$(suffix)'
- name: employeePortalContainerAppName
  value: 'employee-portal-static-$(suffix)'
- name: catalogApiContainerAppName
  value: 'catalog-api-$(suffix)'
- name: customerAuthServerContainerAppName
  value: 'customer-authserver-$(suffix)'
- name: employeeApiContainerAppName
  value: 'employee-api-$(suffix)'
- name: employeeAuthServerContainerAppName
  value: 'employee-authserver-$(suffix)'
- name: basketApiContainerAppName
  value: 'basket-api-$(suffix)'
- name: orderingApiContainerAppName
  value: 'ordering-api-$(suffix)'
- name: paymentProcessorContainerAppName
  value: 'payment-processor-$(suffix)'
- name: sagaProcessorContainerAppName
  value: 'saga-processor-$(suffix)'
- name: catalogApiRepositoryName
  value: 'eshop.catalog.api'
- name: employeeApiRepositoryName
  value: 'eshop.employeemanagement.api'
- name: employeeAuthServerRepositoryName
  value: 'eshop.employeemanagement.authorizationserver'
- name: customerAuthServerRepositoryName
  value: 'eshop.customer.authorizationserver'
- name: employeePortalRepositoryName
  value: 'eshop.ui.employeeportal'
- name: customerPortalRepositoryName
  value: 'eshop.ui.customerportal'
- name: basketApiRepositoryName
  value: 'eshop.basket.api'
- name: orderingApiRepositoryName
  value: 'eshop.ordering.api'
- name: paymentProcessorRepositoryName
  value: 'eshop.payment.processor'
- name: sagaProcessorRepositoryName
  value: 'eshop.saga.processor'
- name: registryServer
  value: 'index.docker.io'
- name: registryUserName
  value: '$(docker-registry-username)' # From variable group
- name: location
  value: 'centralus'
- name: resourceGroupName
  value: 'eshop-docker'
  
jobs:
- job: DeployProxyConfiguration
  displayName: Deploy Reverse Proxy Configs
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: none
  - download: eshop-on-microservices-ci-docker

  - powershell: (Get-Content '$(eshopProxyConfigurationFile)' -Encoding utf8) `
        -replace '__customerPortalContainerAppName__', '$(customerPortalContainerAppName)' `
        -replace '__catalogApiContainerAppName__', '$(catalogApiContainerAppName)' `
        -replace '__customerAuthServerContainerAppName__', '$(customerAuthServerContainerAppName)' `
        -replace '__basketApiContainerAppName__', '$(basketApiContainerAppName)' `
        -replace '__orderingApiContainerAppName__', '$(orderingApiContainerAppName)' `
      | Set-Content '$(eshopProxyConfigurationFile)'
    displayName: Replace Eshop Web App Tokens
    
  - script: cat '$(eshopProxyConfigurationFile)'
    displayName: Eshop Web App Config Display

  - powershell: (Get-Content '$(eshopEmployeePortalProxyConfigurationFile)' -Encoding utf8) `
        -replace '__employeePortalContainerAppName__', '$(employeePortalContainerAppName)' `
        -replace '__catalogApiContainerAppName__', '$(catalogApiContainerAppName)' `
        -replace '__employeeAuthServerContainerAppName__', '$(employeeAuthServerContainerAppName)' `
        -replace '__employeeApiContainerAppName__', '$(employeeApiContainerAppName)' `
      | Set-Content '$(eshopEmployeePortalProxyConfigurationFile)'
    displayName: Replace Eshop Employee Portal Web App Tokens

  - script: cat '$(eshopEmployeePortalProxyConfigurationFile)'
    displayName: Eshop Employee Portal Web App Config Display

  - task: AzureCLI@2
    displayName: Get Storage Account Key
    inputs:
      azureSubscription: '$(azureserviceconnection)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        ACCOUNT_KEY=$(az storage account keys list --account-name $(storageAccountName) --query '[0].value')
        echo "##vso[task.setvariable variable=storageAccountKey;issecret=true]$ACCOUNT_KEY"

  - task: AzureCLI@2
    displayName: Upload Eshop Proxy Configuration To Storage Account
    inputs:
      azureSubscription: '$(azureserviceconnection)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: az storage file upload --account-name $(storageAccountName) --account-key $(storageAccountKey) --share-name $(eshopProxyConfigFileShareName) --path envoy.yaml --source '$(eshopProxyConfigurationFile)'
      
  - task: AzureCLI@2
    displayName: Upload Eshop Employee Portal Proxy Configuration To Storage Account
    inputs:
      azureSubscription: '$(azureserviceconnection)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: az storage file upload --account-name $(storageAccountName) --account-key $(storageAccountKey) --share-name $(eshopEmployeePortalProxyConfigFileShareName) --path envoy.yaml --source '$(eshopEmployeePortalProxyConfigurationFile)'

- job: DeployApps
  displayName: 'Deploy Container Apps'
  strategy: 
   matrix: 
     CatalogApi:
       repository: '$(catalogApiRepositoryName)'
       containerAppName: '$(catalogApiContainerAppName)'
     EmployeeApi:
       repository: '$(employeeApiRepositoryName)'
       containerAppName: '$(employeeApiContainerAppName)'
     EmployeeAuthorizationServer:
       repository: '$(employeeAuthServerRepositoryName)'
       containerAppName: '$(employeeAuthServerContainerAppName)'
     CustomerAuthorizationServer:
       repository: '$(customerAuthServerRepositoryName)'
       containerAppName: '$(customerAuthServerContainerAppName)'
     CustomerPortal:
       repository: '$(customerPortalRepositoryName)'
       containerAppName: '$(customerPortalContainerAppName)'
     EmployeePortal:
       repository: '$(employeePortalRepositoryName)'
       containerAppName: '$(employeePortalContainerAppName)'
     BasketApi:
       repository: '$(basketApiRepositoryName)'
       containerAppName: '$(basketApiContainerAppName)'
     OrderingApi:
       repository: '$(orderingApiRepositoryName)'
       containerAppName: '$(orderingApiContainerAppName)'
     PaymentProcessor:
       repository: '$(paymentProcessorRepositoryName)'
       containerAppName: '$(paymentProcessorContainerAppName)'
     SagaProcessor:
       repository: '$(sagaProcessorRepositoryName)'
       containerAppName: '$(sagaProcessorContainerAppName)'
  pool:
    vmImage: ubuntu-latest

  steps:
  - checkout: none

  - task: AzureContainerApps@1
    displayName: Deploy Container App
    inputs:
      azureSubscription: '$(azureserviceconnection)'
      imageToDeploy: '$(registryServer)/$(registryUserName)/$(repository):$(resources.pipeline.eshop-on-microservices-ci-docker.runID)'
      containerAppName: '$(containerAppName)'
      resourceGroup: '$(resourceGroupName)'
      location: '$(location)'
  
- job: CheckApps
  dependsOn: [DeployApps, DeployProxyConfiguration]
  displayName: 'Chceck Apps Is Healthy'
  pool:
    vmImage: ubuntu-latest

  steps:
  - checkout: none

  - task: AzureCLI@2
    displayName: Get Application FQDN
    inputs:
      azureSubscription: '$(azureserviceconnection)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        FQDN=$(az containerapp show --name $(eshopAppName) --resource-group $(resourceGroupName) --query properties.configuration.ingress.fqdn -otsv)
        echo "##vso[task.setvariable variable=eshopAppFQDN]$FQDN"

  - task: AzureCLI@2
    displayName: Get Application FQDN
    inputs:
      azureSubscription: '$(azureserviceconnection)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        FQDN=$(az containerapp show --name $(eshopEmployeePortalAppName) --resource-group $(resourceGroupName) --query properties.configuration.ingress.fqdn -otsv)
        echo "##vso[task.setvariable variable=eshopEmployeePortalAppFQDN]$FQDN"

  - powershell: Invoke-WebRequest -UseBasicParsing https://$(eshopAppFQDN)/ -TimeoutSec 300
    displayName: Check Eshop App

  - powershell: Invoke-WebRequest -UseBasicParsing https://$(eshopEmployeePortalAppFQDN)/ -TimeoutSec 300
    displayName: Check Eshop Employee Portal App
