# RELEASE PIPELINE (AKS Infrastructure Deployment)

resources:
  repositories:
  - repository: self
    trigger: none
  pipelines:
  - pipeline: eshop-on-microservices-ci-aks
    source: eshop-on-microservices-ci-aks

variables:
- group: microservices-aks-variable-group

- name: azureserviceconnection
  value: 'azure-aks-infrastructure-spn'
- name: suffix
  value: ${{ split(variables['System.TeamProjectId'], '-')[0]}} # Pseudo - random string based on project Id
- name: subscriptionid
  value: '$(subscription-id)' # From variable group
- name: sqlEntraIdAdminLogin
  value: '$(ado-service-principal-id)' # azureserviceconnection  service principal login (will be assigned as administrator)
- name: sqlEntraIdAdminObjectId
  value: '$(ado-service-principal-object-id)' # azureserviceconnection service principal Object Id (will be assigned as administrator)
- name: sqlUserAssignedIdentity
  value: '$(sql-umi-id)' # Identity with directory reader role
- name: acrName
  value: '$(acr-name)'  # From variable group
- name: resourceGroupName
  value: 'eshop-aks'
- name: location
  value: 'centralus' 
- name: employeeSqlServerName
  value: 'employee-sqlserver-$(suffix)'
- name: customerSqlServerName 
  value: 'customer-sqlserver-$(suffix)'
- name: catalogSqlServerName
  value: 'catalog-sqlserver-$(suffix)2'
- name: orderingSqlServerName
  value: 'ordering-sqlserver-$(suffix)'
- name: sagaSqlServerName
  value: 'saga-sqlserver-$(suffix)'
- name: redisCacheName 
  value: 'basket-rediscache-$(suffix)'
- name: serviceBusNamespaceName 
  value: 'eshop-sb-$(suffix)'
- name: dnsLabel
  value: 'eshop-$(suffix)'
- name: clusterName
  value: 'aks-eshop-$(suffix)'
- name: agentCount
  value: 2
- name: agentVMSize
  value: 'Standard_B2s'
- name: aksNamespace
  value: 'eshop'
- name: catalogApiUMIName
  value: 'catalog-api-identity'
- name: employeeManagementUMIName
  value: 'employee-management-identity'
- name: customerAuthServerUMIName 
  value: 'customer-authserver-identity'
- name: basketApiUMIName 
  value: 'basket-api-identity'
- name: orderingApiUMIName 
  value: 'ordering-api-identity'
- name: paymentProcessorUMIName 
  value: 'payment-processor-identity'
- name: sagaProcessorUMIName 
  value: 'saga-processor-identity'

jobs:
- job: DeployInfrastructure
  displayName: Deploy Infrastructure
  pool:
    vmImage: ubuntu-latest

  steps:
  - checkout: none
  - download: eshop-on-microservices-ci-aks

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: Deploy Infrastructure
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: '$(azureserviceconnection)'
      subscriptionId: '$(subscriptionid)'
      action: 'Create Or Update Resource Group'
      resourceGroupName: '$(resourceGroupName)'
      location: '$(location)'
      templateLocation: 'Linked artifact'
      csmFile: '$(Pipeline.Workspace)/eshop-on-microservices-ci-aks/Bicep/main-aks.bicep'
      overrideParameters: ' -catalogSqlServerName $(catalogSqlServerName) -customerSqlServerName $(customerSqlServerName) -employeeSqlServerName $(employeeSqlServerName) -orderingSqlServerName $(orderingSqlServerName) -sagaSqlServerName $(sagaSqlServerName) -sqlEntraIdAdminLogin $(sqlEntraIdAdminLogin) -sqlEntraIdAdminObjectId $(sqlEntraIdAdminObjectId) -sqlUserAssignedIdentity $(sqlUserAssignedIdentity) -acrName $(acrName) -dnsLabel $(dnsLabel) -clusterName $(clusterName) -agentCount $(agentCount) -agentVMSize $(agentVMSize) -aksNamespace $(aksNamespace) -catalogApiUMIName $(catalogApiUMIName) -employeeManagementUMIName $(employeeManagementUMIName) -customerAuthServerUMIName $(customerAuthServerUMIName) -basketApiUMIName $(basketApiUMIName) -orderingApiUMIName $(orderingApiUMIName) -paymentProcessorUMIName $(paymentProcessorUMIName) -sagaProcessorUMIName $(sagaProcessorUMIName)  -redisCacheName $(redisCacheName) -serviceBusNamespaceName $(serviceBusNamespaceName) -location $(location) -suffix $(suffix)'
      deploymentMode: 'Incremental'

- job: DbPermissions
  displayName: Set Db Permissions
  dependsOn: DeployInfrastructure
  pool:
    vmImage: windows-latest
  strategy: 
    matrix:
      CatalogApi:
        umiName: $(catalogApiumiName)
        sqlServerName: $(catalogSqlServerName)
        dbName: 'eshop.catalog.Db'
      CustomerAuthServer:
        umiName: $(customerAuthServerUMIName)
        sqlServerName: $(customerSqlServerName)
        dbName: 'eshop.customer.Db'
      EmployeeManagement:
        umiName: $(employeeManagementUMIName)
        sqlServerName: $(employeeSqlServerName)
        dbName: 'eshop.employee.Db'
      OrderingApi:
        umiName: $(orderingApiUMIName)
        sqlServerName: $(orderingSqlServerName)
        dbName: 'eshop.ordering.Db'
      SagaProcessor:
        umiName: $(sagaProcessorUMIName)
        sqlServerName: $(sagaSqlServerName)
        dbName: 'eshop.saga.Db'
  steps:
  - checkout: none

  - task: SqlAzureDacpacDeployment@1
    displayName: Set DB Permission
    inputs:
      azureSubscription: '$(azureserviceconnection)'
      AuthenticationType: 'servicePrincipal'
      ServerName: '$(sqlServerName).database.windows.net'
      DatabaseName: $(dbName)
      deployType: 'InlineSqlTask'
      SqlInline: |
        IF DATABASE_PRINCIPAL_ID('$(umiName)') IS NULL
        BEGIN
          CREATE USER [$(umiName)] FROM EXTERNAL PROVIDER;
          ALTER ROLE db_datareader ADD MEMBER [$(umiName)];
          ALTER ROLE db_datawriter ADD MEMBER [$(umiName)];
          ALTER ROLE db_ddladmin ADD MEMBER [$(umiName)];
        END
        GO
      IpDetectionMethod: 'AutoDetect'