#BUILD PIPELINE (USES CONTAINER JOBS)

resources:   
 repositories:
    - repository: self
      trigger: none
      # - master 
 containers:
  - container: dotnetsdk
    image: mcr.microsoft.com/dotnet/sdk:7.0
    env:
      ConnectionStrings__employeeDbConnectionString: Server=tcp:mssql;Integrated Security=false;Initial Catalog=eshop.employee.Db;User Id=sa;password=$(sqlPassword);TrustServerCertificate=true
      ConnectionStrings__catalogDbConnectionString: Server=tcp:mssql;Integrated Security=false;Initial Catalog=eshop.catalog.Db;User Id=sa;password=$(sqlPassword);TrustServerCertificate=true
  - container: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    env:
      MSSQL_SA_PASSWORD: $(sqlPassword)
      ACCEPT_EULA: Y
    ports:
      - 1433

variables:
  buildConfiguration: 'Release'
  apiWorkingDirectory: '$(System.DefaultWorkingDirectory)/eshop-api'
  sqlPassword: 'sqlP@ssw0rd'
  publishFolder: 'publish'
  dockerRegistryConnection: 'docker-connection'
  username: $(docker-registry-username)  # Create the "docker-registry-usernamed" pipeline variable in Variables section or replace the expression by the value

jobs:
  - job: test_api
    displayName: Test Api
    pool:
      vmImage: ubuntu-latest
    services:
      mssql: mssql
    container: dotnetsdk

    steps:
      - task: DotNetCoreCLI@2
        name: Restore
        inputs:
          command: 'restore'
          projects: '$(apiWorkingDirectory)/*.sln'

      - task: DotNetCoreCLI@2          
        displayName: Build
        inputs:
          command: 'build'
          arguments: '--configuration $(buildConfiguration)'
          projects: '$(apiWorkingDirectory)/*.sln'

      - task: DotNetCoreCLI@2
        displayName: Run Tests
        inputs:
            command: 'test'
            arguments: '--configuration $(buildConfiguration)  --collect "Code coverage"'
            projects: '$(apiWorkingDirectory)/*.sln'

  - job: build_and_publish
    displayName: Build And Publish (Docker Images And Artifacts)
    dependsOn: test_api
    condition: succeeded()
    pool: 
      vmImage: ubuntu-latest

    steps:            
      - task: DockerCompose@0
        displayName: Build Docker Images
        inputs:
          containerregistrytype: 'Container Registry'
          dockerRegistryEndpoint: '$(dockerRegistryConnection)'
          dockerComposeFile: '$(System.DefaultWorkingDirectory)/docker-compose.yml'
          dockerComposeFileArgs: |
            TAG=$(Build.BuildId)
            DOCKER_REGISTRY=$(username)/
            ANGULAR_CONFIGURATION=production
            APPDATA=
          action: 'Build services'
          includeSourceTags: true
          includeLatestTag: true

      - task: DockerCompose@0
        displayName: Push Docker Images
        inputs:
          containerregistrytype: 'Container Registry'
          dockerRegistryEndpoint: '$(dockerRegistryConnection)'
          dockerComposeFile: '$(System.DefaultWorkingDirectory)/docker-compose.yml'
          dockerComposeFileArgs: |
            TAG=$(Build.BuildId)
            DOCKER_REGISTRY=$(username)/
            ANGULAR_CONFIGURATION=production
            APPDATA=
          action: 'Push services'
          includeSourceTags: true
          includeLatestTag: true
      
      - task: PublishPipelineArtifact@1
        displayName: Publish Pipepile Artifact -  Bicep
        inputs:
          targetPath: '$(System.DefaultWorkingDirectory)/.azure/'
          artifact: 'Bicep'
          publishLocation: 'pipeline'

      - task: PublishPipelineArtifact@1
        displayName: Publish Pipepile Artifact -  NGINX configuration
        inputs:
          targetPath: '$(System.DefaultWorkingDirectory)/nginx-proxy/'
          artifact: 'NGINX'
          publishLocation: 'pipeline'