# RELEASE PIPELINE (Infrastructure Deployment)

resources:
 repositories:
   - repository: self
     trigger: none
 pipelines:
  - pipeline: eshop-on-microservices-ci-docker
    source: eshop-on-microservices-ci-docker

variables:
- group: microservices-variable-group

- name: azureserviceconnection
  value: 'azure-docker-infrastructure-spn'
- name: suffix
  value: ${{ split(variables['System.TeamProjectId'], '-')[0]}} # Pseudo - random string based on project Id
- name: subscriptionid
  value: '$(subscription-id)' # From variable group
- name: sqlEntraIdAdminLogin
  value: '$(ado-service-principal-id)' # azureserviceconnection  service principal login (will be assigned as administrator)
- name: sqlEntraIdAdminObjectId
  value: '$(ado-service-principal-object-id)' # azureserviceconnection service principal Object Id (will be assigned as administrator)
- name: sqlUserAssignedIdentity
  value: '$(sql-umi-id)' # Identity with directory reader role
- name: storageAccountName
  value: 'storageacc$(suffix)'
- name: eshopProxyConfigFileShareName 
  value: 'eshopproxy'
- name: eshopEmployeePortalProxyConfigFileShareName
  value: 'eshopemployeeportalproxy'
- name: eshopAppName
  value: 'eshop-$(suffix)'
- name: eshopEmployeePortalAppName
  value: 'eshop-employee-portal-$(suffix)'
- name: customerPortalContainerAppName
  value: 'customer-portal-static-$(suffix)'
- name: employeePortalContainerAppName
  value: 'employee-portal-static-$(suffix)'
- name: catalogApiContainerAppName
  value: 'catalog-api-$(suffix)'
- name: customerAuthServerContainerAppName
  value: 'customer-authserver-$(suffix)'
- name: employeeApiContainerAppName
  value: 'employee-api-$(suffix)'
- name: employeeAuthServerContainerAppName
  value: 'employee-authserver-$(suffix)'
- name: basketApiContainerAppName
  value: 'basket-api-$(suffix)'
- name: orderingApiContainerAppName
  value: 'ordering-api-$(suffix)'
- name: paymentProcessorContainerAppName
  value: 'payment-processor-$(suffix)'
- name: sagaProcessorContainerAppName
  value: 'saga-processor-$(suffix)'
- name: employeeSqlServerName
  value: 'employee-sqlserver-$(suffix)'
- name: customerSqlServerName
  value: 'customer-sqlserver-$(suffix)'
- name: catalogSqlServerName
  value: 'catalog-sqlserver-$(suffix)1'
- name: orderingSqlServerName
  value: 'ordering-sqlserver-$(suffix)'
- name: sagaSqlServerName
  value: 'saga-sqlserver-$(suffix)'
- name: sqlDbName
  value: 'eshop.Db'
- name: employeeOAuthIssuer
  value: ''
- name: employeeOAuthMetadataEndpoint
  value: ''
- name: employeeOAuthAudience
  value: ''
- name: registryServer
  value: 'index.docker.io'
- name: registryUserName
  value: '$(docker-registry-username)' # From variable group
- name: registryPassword
  value: '$(docker-registry-read-token)' # From variable group
- name: location
  value: 'centralus'
- name: resourceGroupName
  value: 'eshop-docker'

jobs:
- job: DeployInfrastructure
  displayName: Deploy Infrastructure
  pool:
    vmImage: ubuntu-latest

  steps:
  - checkout: none
  - download: eshop-on-microservices-ci-docker

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: Deploy Infrastructure
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: '$(azureserviceconnection)'
      subscriptionId: '$(subscriptionid)'
      action: 'Create Or Update Resource Group'
      resourceGroupName: '$(resourceGroupName)'
      location: '$(location)'
      templateLocation: 'Linked artifact'
      csmFile: '$(Pipeline.Workspace)/eshop-on-microservices-ci-docker/Bicep/main-docker.bicep'
      overrideParameters: '-dbName $(sqlDbName) -catalogSqlServerName $(catalogSqlServerName) -customerSqlServerName $(customerSqlServerName) -employeeSqlServerName $(employeeSqlServerName) -orderingSqlServerName $(orderingSqlServerName) -sagaSqlServerName $(sagaSqlServerName) -sqlEntraIdAdminLogin $(sqlEntraIdAdminLogin) -sqlEntraIdAdminObjectId $(sqlEntraIdAdminObjectId) -sqlUserAssignedIdentity $(sqlUserAssignedIdentity) -eshopEmployeePortalAppName $(eshopEmployeePortalAppName) -eshopAppName $(eshopAppName) -customerPortalContainerAppName $(customerPortalContainerAppName) -employeePortalContainerAppName $(employeePortalContainerAppName) -catalogApiContainerAppName $(catalogApiContainerAppName) -customerAuthServerContainerAppName $(customerAuthServerContainerAppName) -employeeApiContainerAppName $(employeeApiContainerAppName) -employeeAuthServerContainerAppName $(employeeAuthServerContainerAppName) -basketApiContainerAppName $(basketApiContainerAppName) -orderingApiContainerAppName $(orderingApiContainerAppName) -paymentProcessorContainerAppName $(paymentProcessorContainerAppName) -sagaProcessorContainerAppName $(sagaProcessorContainerAppName) -storageAccountName $(storageAccountName)  -eshopProxyConfigFileShareName $(eshopProxyConfigFileShareName) -eshopEmployeePortalProxyConfigFileShareName $(eshopEmployeePortalProxyConfigFileShareName) -employeeOAuthIssuer $(employeeOAuthIssuer) -employeeOAuthMetadataEndpoint $(employeeOAuthMetadataEndpoint) -employeeOAuthAudience $(employeeOAuthAudience) -registryServer $(registryServer) -registryUserName $(registryUserName) -registryPassword $(registryPassword) -revisionSuffix $(Build.BuildId) -location $(location) -suffix $(suffix)'
      deploymentMode: 'Incremental'

- job: DbPermissions
  displayName: Set Db Permissions
  dependsOn: DeployInfrastructure
  pool:
    vmImage: windows-latest
  strategy: 
    matrix:
      CatalogApi:
        containerAppName: $(catalogApiContainerAppName)
        sqlServerName: $(catalogSqlServerName)
      CustomerAuthServer:
        containerAppName: $(customerAuthServerContainerAppName)
        sqlServerName: $(customerSqlServerName)
      EmployeeApi:
        containerAppName: $(employeeApiContainerAppName)
        sqlServerName: $(employeeSqlServerName)
      EmployeeAuthServer:
        containerAppName: $(employeeAuthServerContainerAppName)
        sqlServerName: $(employeeSqlServerName)
      OrderingApi:
        containerAppName: $(orderingApiContainerAppName)
        sqlServerName: $(orderingSqlServerName)
      SagaProcessor:
        containerAppName: $(sagaProcessorContainerAppName)
        sqlServerName: $(sagaSqlServerName)
  steps:
  - checkout: none

  - task: SqlAzureDacpacDeployment@1
    displayName: Set DB Permission
    inputs:
      azureSubscription: '$(azureserviceconnection)'
      AuthenticationType: 'servicePrincipal'
      ServerName: '$(sqlServerName).database.windows.net'
      DatabaseName: '$(sqlDbName)'
      deployType: 'InlineSqlTask'
      SqlInline: |
        IF DATABASE_PRINCIPAL_ID('$(containerAppName)') IS NULL
        BEGIN
          CREATE USER [$(containerAppName)] FROM EXTERNAL PROVIDER;
          ALTER ROLE db_datareader ADD MEMBER [$(containerAppName)];
          ALTER ROLE db_datawriter ADD MEMBER [$(containerAppName)];
          ALTER ROLE db_ddladmin ADD MEMBER [$(containerAppName)];
        END
        GO
      IpDetectionMethod: 'AutoDetect'