apiVersion: v1
kind: ServiceAccount
metadata:
  {{ if .Values.useAks -}}
  annotations:
    azure.workload.identity/client-id: "{{ .Values.azure.basketApiUmiClientId }}"
  labels:
    azure.workload.identity/use:  "true"
{{- end }}        
  name: {{ .Values.basket_api.serviceAccountName }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.basket_api.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.basket_api.appName }}
  replicas: {{ .Values.basket_api.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.basket_api.appName }}
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: {{ .Values.basket_api.serviceAccountName }}
      containers:
      - name: {{ .Values.basket_api.appName }}
        image: "{{ .Values.dockerRegistry }}/{{ .Values.basket_api.image.repository }}:{{ .Values.imagesTag }}"
        imagePullPolicy: IfNotPresent
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.basket_api.env.ASPNETCORE_ENVIRONMENT }}
        - name: ASPNETCORE_HTTP_PORTS
          value: "8080"
        {{ if .Values.useAks -}}
        - name: ConnectionStrings__entraIdRedisConnectionString
          value: {{ .Values.azure.redisCacheName }}.redis.cache.windows.net:6380   
        - name: broker__AzureServiceBusConnectionString
          value: sb://{{ .Values.azure.serviceBusNamespaceName }}.servicebus.windows.net      
        {{- else -}}
        - name: ConnectionStrings__redisConnectionString
          value: {{ .Values.redis.appName }}:{{ .Values.redis.servicePort }}
        - name: broker__rabbitMQHost
          value: {{ .Values.rabbitmq.appName }}
        {{- end }}  
        - name: JWTSettings__Issuer
          value: "https://{{ .Values.eshop_ingress.eshopDnsName }}/authorize"
        - name: JWTSettings__MetadataAddress
          value: "http://{{ .Values.customer_authserver.appName }}/authorize/.well-known/openid-configuration"
        resources:
          limits:
            memory: {{ .Values.basket_api.resources.memory }}
            cpu: {{ .Values.basket_api.resources.cpu }}
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /hc
            port: 8080
          initialDelaySeconds: 30  
          periodSeconds: 10        
          failureThreshold: 1
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /hc
            port: 8080
          initialDelaySeconds: 30  
          periodSeconds: 30        
          failureThreshold: 3

      {{ if .Values.imagePullSecretName -}}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecretName }}
      {{- end }}          
    
---
apiVersion: v1
kind: Service
metadata: 
  name: {{ .Values.basket_api.appName }}
spec:
  selector:
    app: {{ .Values.basket_api.appName  }}
  type: ClusterIP
  ports:
  - protocol: 'TCP'
    port: 80
    targetPort: 8080