apiVersion: v1
kind: ServiceAccount
metadata:
  {{ if .Values.useAks -}}
  annotations:
    azure.workload.identity/client-id: "{{ .Values.azure.catalogApiUmiClientId }}"
  labels:
    azure.workload.identity/use:  "true"
{{- end }}        
  name: {{ .Values.catalog_api.serviceAccountName }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.catalog_api.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.catalog_api.appName }}
  replicas: {{ .Values.catalog_api.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.catalog_api.appName }}
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: {{ .Values.catalog_api.serviceAccountName }}
      containers:
      - name: {{ .Values.catalog_api.appName }}
        image: "{{ .Values.dockerRegistry }}/{{ .Values.catalog_api.image.repository }}:{{ .Values.imagesTag }}" 
        imagePullPolicy: IfNotPresent
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.catalog_api.env.ASPNETCORE_ENVIRONMENT }}
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: ConnectionStrings__catalogDbConnectionString            
          value: {{ template "catalog-api.connectionString" . }}
        {{ if .Values.useAks -}}
        - name: broker__AzureServiceBusConnectionString
          value: sb://{{ .Values.azure.serviceBusNamespaceName }}.servicebus.windows.net      
        {{- else -}}
        - name: broker__rabbitMQHost
          value: {{ .Values.rabbitmq.appName }}
        {{- end }} 
        - name: initDbOnStartup
          value: "{{ .Values.catalog_api.env.initDbOnStartup }}"
        - name: generatedItemPictureUriHost
          value: /catalog
        - name: clients
          value: "https://{{ .Values.eshop_ingress.eshopEmployeePortalDnsName }},https://{{ .Values.eshop_ingress.eshopDnsName }}"
        - name: EmployeeJWTSettings__Issuer
          value: {{ template "employee-authorization-server.OAuthIssuer" . }}
        - name: EmployeeJWTSettings__MetadataAddress
          value: {{ template "employee-authorization-server.OAuthMetadataAddress" . }}
        - name: EmployeeJWTSettings__Audience
          value: {{ template "employee-authorization-server.OAuthAudience" . }}
        - name: CustomerJWTSettings__Issuer
          value: "https://{{ .Values.eshop_ingress.eshopDnsName }}/authorize"
        - name: CustomerJWTSettings__MetadataAddress
          value: "https://{{ .Values.eshop_ingress.eshopDnsName }}/authorize/.well-known/openid-configuration"      
        resources:
          limits:
            memory:  {{ .Values.catalog_api.resources.memory }}
            cpu:  {{ .Values.catalog_api.resources.cpu }}
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /hc
            port: 80
          initialDelaySeconds: 30  
          periodSeconds: 30        
          failureThreshold: 1
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /hc
            port: 80
          initialDelaySeconds: 30  
          periodSeconds: 30        
          failureThreshold: 3
      
      {{ if .Values.imagePullSecretName -}}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecretName }}
      {{- end }}             

---

apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.catalog_api.appName }}
spec:
  selector:
    app:  {{ .Values.catalog_api.appName }}
  type:  ClusterIP
  ports:
  - protocol: 'TCP'
    port: 80