{{ if .Values.useAks -}}

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-imds-access
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress: 
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
          except: 
          - 169.254.169.254/32
          
---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-imds-for-kv-provider
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.secrets_provider.appName }}
  policyTypes:
  - Egress
  egress: 
    - to:
      - ipBlock:
          cidr: 169.254.169.254/32

{{- end }}  
