{{ if .Values.useAks -}}

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akv-encryption-keys
spec:
  provider: azure
  secretObjects:                          
    - secretName: {{ .Values.azure.akvClientSigningSecretName }}
      type: Opaque
      data: 
        - objectName: {{ .Values.azure.akvClientSigningSecretName }}
          key: jwt                       
    - secretName: {{ .Values.azure.akvEmployeeSigningSecretName }}
      type: Opaque
      data: 
        - objectName: {{ .Values.azure.akvEmployeeSigningSecretName }}
          key: jwt                    
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.azure.aksUmiClientId }}
    keyvaultName: {{ .Values.azure.akvName }}                # the name of the AKV instance
    objects: |
      array:
        - |
          objectName: {{ .Values.azure.akvClientSigningSecretName }}
          objectType: secret   
        - |
          objectName: {{ .Values.azure.akvEmployeeSigningSecretName }}
          objectType: secret           
    tenantId: {{ .Values.azure.tenantId }}                # the tenant ID of the AKV instance

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.secrets_provider.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.secrets_provider.appName }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.secrets_provider.appName }}    
        azure.workload.identity/use: "true"
    spec:
      containers:
      - name: {{ .Values.secrets_provider.appName }}
        image: "nginx:1.25.3"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/keys/
          name:  akv-encryption-keys
          readOnly: true      
      volumes:
        - name: akv-encryption-keys
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: akv-encryption-keys

{{- end }}  
